image: Visual Studio 2017
version: 0.0.{build}

init:
    - git config --global core.autocrlf input

branches:
  only:
    - master

clone_folder: c:\Kontur.ImageTransformer
shallow_clone: true

matrix:
    fast_finish: false

platform:
    - Any CPU

configuration:
    - Release

environment:
    matrix:
        - TOOLCHAIN: msvc14

build_script:
    - nuget restore && msbuild /p:Configuration=Release

test:
    assemblies:
        - Kontur.ImageTransformerTests.dll
